# fly.toml app configuration file generated for full-stack-open-pokedex-hidden-dream-4870 on 2025-09-27T11:04:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-app-pznvuq'
primary_region = 'lhr'

[build]

[deploy]
  strategy = "canary"

[env]
  PORT = "5001" # add this where PORT matches the internal_port below

[processes]
  app = "node app.js" # add this

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


